FROM docker.io/library/node:19.1.0@sha256:bff0e689cb433913ab411af7a58253d54c7fd8c3134ffeb25287cdf24d9a5972

WORKDIR /app

COPY ./package.json ./pnpm-lock.yaml* ./
COPY ./.npmrc ./

RUN npm install pnpm@8.4.0 -g && pnpm install --frozen-lockfile

COPY . .

EXPOSE 8000
ENTRYPOINT ["/bin/sh", "-c", "pnpm run start:dev"]